### ISSUE TITLE
Is "tx size" from the document always be `fixed size` ?

### ISSUE THREAD

**Issue by lyp830414** [SamYuan1990/Probe#81]
- **If the transations are from different chaincode's method:**
        i.e,  one tx aims to set a value (Key xxx: Value(int)), that maybe a short size of the transaction
               another tx aims to  store huge data(Key: xxx, value (big-array-bytes)), that maybe a size gap to the tx size according to previous one ?

- **Then , from the document:**
       I learnt that the block_size can be caculated by block size = min(PreferredMaxBytes，MaxMessageCount * tx size， AbsoluteMaxBytes), but ... if the tx size differs from each transaction, will the result maybe not such precise? (Or, tape use a unique chaincode method for testing, so tx should be always fixed size. )
     （For `tx size` understanding, I‘m not sure whether it should be a `tape`'s question :-) ）
@SamYuan1990

**Comment by SamYuan1990** [comment]
your 1st question will be supported by https://github.com/Hyperledger-TWGC/tape/issues/109.
the second one, general speaking, you can calculate avg size instead.

at my point of view, when taking about tx size, it should be considered from one case to avg/mixed case.
as every tx has it's own size. even we do a simple logic as `counting() { read i;i++; write i; }` the size is different for each tx due to cert, and value of i. (`9 -> 10, 99 -> 100 ...`)

so, it should be considered as avg size of tx.

and it's possible to calculate/get the avg size of tx by statistics...

**Comment by lyp830414** [comment]
Got that . Thankyou! Now close it..
@SamYuan1990

**Comment by lyp830414** [comment]
Now I have known what does the tx size mean from view of tape/probe.
